export const OBJECTS_LIST_REQUEST = "OBJECTS_LIST_REQUEST";
export const OBJECTS_LIST_SUCCESS = "OBJECTS_LIST_SUCCESS";
export const OBJECTS_LIST_FAIL = "OBJECTS_LIST_FAIL";

export const OBJECT_DELETE_REQUEST = "OBJECT_DELETE_REQUEST";
export const OBJECT_DELETE_SUCCESS = "OBJECT_DELETE_SUCCESS";
export const OBJECT_DELETE_FAIL = "OBJECT_DELETE_FAIL";

export const OBJECT_SHORTLIST_REQUEST = "OBJECT_SHORTLIST_REQUEST";
export const OBJECT_SHORTLIST_SUCCESS = "OBJECT_SHORTLIST_SUCCESS";
export const OBJECT_SHORTLIST_FAIL = "OBJECT_SHORTLIST_FAIL";

export const REMOVE_SHORTLIST_REQUEST = "REMOVE_SHORTLIST_REQUEST";
export const REMOVE_SHORTLIST_SUCCESS = "REMOVE_SHORTLIST_SUCCESS";
export const REMOVE_SHORTLIST_FAIL = "REMOVE_SHORTLIST_FAIL";

export const SHORTLISTED_LIST_REQUEST = "SHORTLISTED_LIST_REQUEST";
export const SHORTLISTED_LIST_SUCCESS = "SHORTLISTED_LIST_SUCCESS";
export const SHORTLISTED_LIST_FAIL = "SHORTLISTED_LIST_FAIL";

export const REMOVE_SHORTLISTED_REQUEST = "REMOVE_SHORTLISTED_REQUEST";
export const REMOVE_SHORTLISTED_SUCCESS = "REMOVE_SHORTLISTED_SUCCESS";
export const REMOVE_SHORTLISTED_FAIL = "REMOVE_SHORTLISTED_FAIL";

export const SORTED_LIST_REQUEST = "SORTED_LIST_REQUEST";
export const SORTED_LIST_SUCCESS = "SORTED_LIST_SUCCESS";
export const SORTED_LIST_FAIL = "SORTED_LIST_FAIL";

export const ADD_OBJECT_REQUEST = "ADD_OBJECT_REQUEST";
export const ADD_OBJECT_SUCCESS = "ADD_OBJECT_SUCCESS";
export const ADD_OBJECT_FAIL = "ADD_OBJECT_FAIL";
